### ISSUE TITLE
C++11 shared pointers?

### ISSUE THREAD

**Issue by JoshKlint** [lubyk/dub#15]
Hi, I am looking for a Lua binding library with support for C++11 shared pointers for Leadwerks Game Engine 5. Previously, we used ToLua++. Does Dub support this?

**Comment by gaspard** [comment]
Hi there, It's been a time since I was involved with Lua... I used reference counting with dub when creating bindings to bullet physics.

Have you looked at the docs: https://lubyk.github.io/lubyk/dub.html ?
