### ISSUE TITLE
header_base does not work for directories with special characters

### ISSUE THREAD

**Issue by hendrik-cliqz** [lubyk/dub#8]
it took some effort to find out why 'header_base' did not work for me:

I have a directory in my path with a '-' (e.g. 'git-test'), for those the string matching in: https://github.com/lubyk/dub/blob/master/dub/LuaBinder.lua#L598 does not match as the '-' is interpreted as pattern, in order to match literally it needs to be escaped: '-' -> '%-'

I can make a workaround for it in my binding script but the right way would be to fix it in LuaBinder.lua

**Comment by hendrik-cliqz** [comment]
Thanks!

**Comment by gaspard** [comment]
I am pushing the new rock to luarocks (but I need to push other rocks with lua 5.3 compatibility at the same time). Should be finished today.

**Comment by gaspard** [comment]
Done. dub 2.2.2 is out.
